### ISSUE TITLE
Slicer extension build failure

### ISSUE THREAD

**Issue by lassoan** [sebastianandress/Slicer-SurfaceFragmentsRegistration#1]
I'm reviewing extension builds for latest Slicer-4.13 version. This extension fails to build for current Slicer version:

```
CMake Error: Could not find cmake module file: CMakeDetermineFragmentsCompiler.cmake
CMake Error: Could not find cmake module file: D:/D/P/S-0-E-b/SurfaceFragmentsRegistration-build/CMakeFiles/3.22.1/CMakeFragmentsCompiler.cmake
CMake Error: Could not find cmake module file: CMakeDetermineRegistrationCompiler.cmake
CMake Error: Could not find cmake module file: D:/D/P/S-0-E-b/SurfaceFragmentsRegistration-build/CMakeFiles/3.22.1/CMakeRegistrationCompiler.cmake
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_Fragments_COMPILER could be found.

CMake Error: Could not find cmake module file: CMakeFragmentsInformation.cmake
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_Registration_COMPILER could be found.
```

(https://slicer.cdash.org/build/2578479)

Would you like to keep this extension available? Do you need help with resolving this error?

**Comment by lassoan** [comment]
We would like to keep the nightly extension dashboard clean and therefore we stop attempting building all extensions that are known to fail. Since this extension has a build error and we have not heard from you if you want to fix it, we'll move this extension to the archives.

If you tell us anytime that you want to fix the the build error then we can work with you to resolve the problem and put back the extension to the Extensions Index.

**Comment by sebastianandress** [comment]
Sorry for the very late response. Actually I'm not quite sure about this issue. Could the error be thrown because the project in the CMakeLists file contains spaces?

`project(Surface Fragments Registration)`

https://github.com/sebastianandress/Slicer-SurfaceFragmentsRegistration/blob/5cac8590fe6e459747c913f77aaf3c7242890ea8/CMakeLists.txt#L3

Thanks for your help!

**Comment by lassoan** [comment]
Yes, spaces in project name was one of the issues, there was another minor one. I've fixed both in this pull request: https://github.com/sebastianandress/Slicer-SurfaceFragmentsRegistration/pulls

Please merge and then I can re-enable the nightly builds.

**Comment by sebastianandress** [comment]
Thank you very much, I merched the commit!

**Comment by lassoan** [comment]
OK! I've re-enabled the build now. Hopefully the extension will appear in the Extensions Manager tomorrow.
